### ISSUE TITLE
项目管理者的功能希望能加强

### ISSUE THREAD

**Issue by zgshe** [a54552239/pearProject#15]
希望项目管理者在项目中能更方便的看到各成员的完成状况，现在要看到某个成员的任务，操作路径是“工作台-->团队成员-->具体成员-->任务安排”，而且在任务安排列表中只能筛选未完成和已完成的任务，但在未完成的任务中，逾期未完成的不会直接在列表中提示逾期。
我觉得项目管理者在工作台中点进具体项目时，应该点击任务条目右上角的执行者头像就可以快速进入到该成员的所有任务列表，因为一般都是看到任务逾期或者想给Ta分配新任务时，想看看该成员手中任务情况再进行分析。目前的操作方式感觉有些繁琐，而且成员的任务列表中显示的信息太少

**Comment by a54552239** [comment]
感谢建议，后面会针对这块做优化

**Comment by a54552239** [comment]
2.8.5版本已做初步优化 https://github.com/a54552239/pearProject/commit/d5d12f7956f52321d8d417d08dfb24d77bfed4e3
