### ISSUE TITLE
this.reload()  目录丢失

### ISSUE THREAD

**Issue by lvyandi** [a54552239/pearProject#18]

**Comment by a54552239** [comment]
希望能更详细地描述遇到的问题

**Comment by lvyandi** [comment]
点击项目进去后，如果显示左侧菜单栏，在点击刷新按钮后左侧菜单栏会消失。

**Comment by lvyandi** [comment]
您当前的项目是没显示左侧菜单栏的，我该修改了一下，点击一个项目进去之后继续显示左侧菜单，刷新会导致左侧菜单消失，一级菜单还保留，

**Comment by a54552239** [comment]
可以修改 src/router/home.js 第10行为   meta: {model: 122, info: {show_slider: true, is_inner: false}},
