### ISSUE TITLE
未开启外workerman组建时，其他接口正常。分配任务接口报异常

### ISSUE THREAD

**Issue by DanielZhao1990** [a54552239/pearProject#2]
![image](https://user-images.githubusercontent.com/4916621/55302829-a2c16180-5475-11e9-96b5-888435412289.png)

```
"stream_socket_client(): unable to connect to tcp://192.168.90.34:2346 (����Ŀ����������ܾ����޷����ӡ�
↵)"
```

**Comment by a54552239** [comment]
修改接口文件：config/config.php，将 notice_push 设置 为 false 关闭消息推送
