### ISSUE TITLE
存储桶等配置密钥泄露

### ISSUE THREAD

**Issue by breath-co2** [a54552239/pearProject#26]
线上链接： https://beta.vilson.xyz/index.php/project/index/systemConfig

可以直接访问到，里面包含了七牛的授权配置，微信appkey、oss设置等等

**Comment by breath-co2** [comment]
这些隐私数据不应该传给web（即便登录了）

**Comment by isdotjim** [comment]
搭个车...
想邀请Repo参与者来w3c.group创建项目的对应小组。w3c.group是类似知识星球的社群工具，小组可设置为付费且有赞助功能，同时也是一个区块链主导的创作者社区。这是相关介绍：
http://t.cn/Ai1vLcCU
http://t.cn/Ai1vLcCG
http://t.cn/Ai1vLcCA

**Comment by a54552239** [comment]
感谢指出，已修复
