### ISSUE TITLE
项目管理中的文件管理功能增强

### ISSUE THREAD

**Issue by zgshe** [a54552239/pearProject#29]
你好，看了文件管理，有两个建议，看能否解决：
1、项目管理中的文件目前都是扁平化管理，在一个项目中，不同类型的文件往往是分类管理存放的，能否增加“文件夹”的管理方式？
2、部分文件可能需要进行编辑，目前管理方式需要下载编辑后再进行上传，能否做成“有道云协作”当中的方式，编辑时可用本地office软件打开，保存关闭后自动上传覆盖。作为轻量级的项目管理软件，只增加每次修改的文档的版本管理即可，同一文档的多人同时编辑我觉得没必要，在用户编辑时，对该文档进行锁定。

**Comment by a54552239** [comment]
文件管理这块会做优化，但暂时不考虑在线编辑的方式
