### ISSUE TITLE
好像编译出错了？

### ISSUE THREAD

**Issue by JustBeLeo** [a54552239/pearProject#37]
`
Module Warning (from ./node_modules/eslint-loader/index.js):
error: 'oldVal' is defined but never used (no-unused-vars) at src/views/project/space/files.vue:203:33:
  201 |         watch: {
  202 |             uploader: {
> 203 |                 handler(newVal, oldVal) {
      |                                 ^
  204 |                     //监听是否有上传文件行为
  205 |                     const files = newVal.fileList;
  206 |                     const index = files.findIndex(item => item.projectName == this.project.name);

1 error found.

Module Warning (from ./node_modules/eslint-loader/index.js):
error: 'range' is defined but never used (no-unused-vars) at src/mixins/pagination.js:9:36:
   7 |                 pageSize: 10,
   8 |                 total: 0,
>  9 |                 showTotal: (total, range) => `共 ${total} 条`
     |                                    ^
  10 |             },
  11 |             // requestData: {
  12 |             //     page: this.pagination.page,

1 error found.

Module Warning (from ./node_modules/eslint-loader/index.js):
error: 'relativelyTaskTime' is defined but never used (no-unused-vars) at src/components/project/taskTag.vue:78:29:
  76 |     import {list, del} from "../../api/taskTag";
  77 |     import pagination from "../../mixins/pagination";
> 78 |     import {formatTaskTime, relativelyTaskTime} from "../../assets/js/dateTime";
     |                             ^
  79 |     import {getListByTaskTag} from "../../api/task";
  80 |     import moment from "moment";
  81 | 

error: 'val' is defined but never used (no-unused-vars) at src/components/project/taskTag.vue:108:20:
  106 |                 this.init();
  107 |             },
> 108 |             tabKey(val) {
      |                    ^
  109 |                 this.getTaskList();
  110 |             }
  111 | 

error: 'delFile' is not defined (no-undef) at src/components/project/taskTag.vue:204:33:
  202 |                             cancelText: '再想想',
  203 |                             onOk() {
> 204 |                                 delFile(item.code).then((res) => {
      |                                 ^
  205 |                                     if (!checkResponse(res)) {
  206 |                                         return;
  207 |                                     }

3 errors found.

Module Warning (from ./node_modules/eslint-loader/index.js):
error: 'relativelyTime' is defined but never used (no-unused-vars) at src/components/layout/header/HeaderNotice.vue:123:13:
  121 |     import {showMsgNotification} from "../../../assets/js/notify";
  122 |     import {selfList} from "../../../api/task";
> 123 |     import {relativelyTime} from "../../../assets/js/dateTime";
      |             ^
  124 | 
  125 |     export default {
  126 |         name: 'HeaderNotice',

1 error found.

Module Warning (from ./node_modules/eslint-loader/index.js):
error: 'res' is defined but never used (no-unused-vars) at src/components/project/projectConfig.vue:654:59:
  652 |                     if (this.taskWorkflow) {
  653 |                         submitData.taskWorkflowCode = this.taskWorkflow.code;
> 654 |                         EditTaskWorkflow(submitData).then(res => {
      |                                                           ^
  655 |                             this.getTaskWorkflowList();
  656 | 
  657 |                         });

error: 'res' is defined but never used (no-unused-vars) at src/components/project/projectConfig.vue:660:59:
  658 |                     } else {
  659 |                         submitData.projectCode = this.code;
> 660 |                         saveTaskWorkflow(submitData).then(res => {
      |                                                           ^
  661 |                             this.getTaskWorkflowList();
  662 |                         });
  663 |                     }

error: Unexpected console statement (no-console) at src/components/project/projectConfig.vue:745:17:
  743 |             },
  744 |             workflowRuleChange(value, name) {
> 745 |                 console.log(value);
      |                 ^
  746 |                 console.log(name);
  747 |                 if (name == 'firstAction.action') {
  748 |                     this.currentTaskWorkflowRule.firstAction.value = '';

error: Unexpected console statement (no-console) at src/components/project/projectConfig.vue:746:17:
  744 |             workflowRuleChange(value, name) {
  745 |                 console.log(value);
> 746 |                 console.log(name);
      |                 ^
  747 |                 if (name == 'firstAction.action') {
  748 |                     this.currentTaskWorkflowRule.firstAction.value = '';
  749 |                 }

4 errors found.

Module Warning (from ./node_modules/eslint-loader/index.js):
error: 'res' is defined but never used (no-unused-vars) at src/views/members/profile.vue:326:52:
  324 |             },
  325 |             syncDetail() {
> 326 |                 syncDetail({code: this.code}).then(res => {
      |                                                    ^
  327 |                     this.getMember();
  328 |                 });
  329 |             },

error: 'obj' is defined but never used (no-unused-vars) at src/views/members/profile.vue:343:28:
  341 |                 })
  342 |             },
> 343 |             changeTaskType(obj) {
      |                            ^
  344 |                 this.$nextTick(() => {
  345 |                     this.getTasks();
  346 |                 })

2 errors found.

Module Warning (from ./node_modules/eslint-loader/index.js):
error: 'res' is defined but never used (no-unused-vars) at src/views/notify/notice.vue:147:49:
  145 |                         cancelText: '取消',
  146 |                         onOk() {
> 147 |                             del(record.id).then(res => {
      |                                                 ^
  148 |                                 app.init();
  149 |                             });
  150 |                             return Promise.resolve();

error: 'values' is defined but never used (no-unused-vars) at src/views/notify/notice.vue:159:27:
  157 |                 let app = this;
  158 |                 app.searchForm.validateFields(
> 159 |                     (err, values) => {
      |                           ^
  160 |                         if (!err) {
  161 |                             app.search();
  162 |                         }

2 errors found.

Module Warning (from ./node_modules/eslint-loader/index.js):
error: 'res' is defined but never used (no-unused-vars) at src/views/notify/system.vue:146:49:
  144 |                         cancelText: '取消',
  145 |                         onOk() {
> 146 |                             del(record.id).then(res => {
      |                                                 ^
  147 |                                 app.init();
  148 |                             });
  149 |                             return Promise.resolve();

error: 'values' is defined but never used (no-unused-vars) at src/views/notify/system.vue:158:27:
  156 |                 let app = this;
  157 |                 app.searchForm.validateFields(
> 158 |                     (err, values) => {
      |                           ^
  159 |                         if (!err) {
  160 |                             app.search();
  161 |                         }

2 errors found.

Module Warning (from ./node_modules/eslint-loader/index.js):
error: 'setStore' is defined but never used (no-unused-vars) at src/views/member/login.vue:135:13:
  133 |     import {getStore} from '@/assets/js/storage'
  134 |     import {checkInstall} from "../../api/common/common";
> 135 |     import {setStore} from "../../assets/js/storage";
      |             ^
  136 |     import {_checkLogin} from "../../api/user";
  137 |     import {dingTalkLoginByCode, dingTalkOauth} from "../../api/oauth";
  138 |     import {notice} from "../../assets/js/notice";

error: 'hide' is assigned a value but never used (no-unused-vars) at src/views/member/login.vue:268:31:
  266 |                         }, 1000);
  267 | 
> 268 |                         const hide = this.$message.loading('验证码发送中..', 0);
      |                               ^
  269 |                         getCaptcha(values.mobile)
  270 |                             .then(res => {
  271 |                                 this.$message.destroy();

error: Unexpected console statement (no-console) at src/views/member/login.vue:321:25:
  319 |                             redirect = config.HOME_PAGE + '/' + org.code
  320 |                         }
> 321 |                         console.log('redirect');
      |                         ^
  322 |                         console.log(redirect);
  323 |                         this.$router.push({
  324 |                             path: redirect

error: Unexpected console statement (no-console) at src/views/member/login.vue:322:25:
  320 |                         }
  321 |                         console.log('redirect');
> 322 |                         console.log(redirect);
      |                         ^
  323 |                         this.$router.push({
  324 |                             path: redirect
  325 |                         });

4 errors found.

Module Warning (from ./node_modules/eslint-loader/index.js):
error: 'startStop' is assigned a value but never used (no-unused-vars) at src/assets/js/dateTime.js:9:9:
   7 | export const getWeekDay = () => {
   8 |     //起止日期数组
>  9 |     var startStop = [];
     |         ^
  10 |     //获取当前时间
  11 |     var currentDate = new Date();
  12 |     //返回date是一周中的某一天

error: 'month' is assigned a value but never used (no-unused-vars) at src/assets/js/dateTime.js:15:9:
  13 |     var week = currentDate.getDay();
  14 |     //返回date是一个月中的某一天
> 15 |     var month = currentDate.getDate();
     |         ^
  16 | 
  17 |     //一天的毫秒数
  18 |     var millisecond = 1000 * 60 * 60 * 24;

2 errors found.

Module Warning (from ./node_modules/eslint-loader/index.js):
error: 'to' is defined but never used (no-unused-vars) at src/components/project/taskDetail.vue:1237:20:
  1235 |         },
  1236 |         watch: {
> 1237 |             $route(to, from) {
       |                    ^
  1238 |                 // if (from.name == 'taskdetail') {
  1239 |                 //     this.init();
  1240 |                 // }

error: 'from' is defined but never used (no-unused-vars) at src/components/project/taskDetail.vue:1237:24:
  1235 |         },
  1236 |         watch: {
> 1237 |             $route(to, from) {
       |                        ^
  1238 |                 // if (from.name == 'taskdetail') {
  1239 |                 //     this.init();
  1240 |                 // }

error: 'oldVal' is defined but never used (no-unused-vars) at src/components/project/taskDetail.vue:1259:33:
  1257 |             },
  1258 |             uploader: {
> 1259 |                 handler(newVal, oldVal) {
       |                                 ^
  1260 |                     //监听是否有上传文件行为
  1261 |                     console.log(newVal);
  1262 |                     console.log(newVal.fileList);

error: Unexpected console statement (no-console) at src/components/project/taskDetail.vue:1261:21:
  1259 |                 handler(newVal, oldVal) {
  1260 |                     //监听是否有上传文件行为
> 1261 |                     console.log(newVal);
       |                     ^
  1262 |                     console.log(newVal.fileList);
  1263 |                     const files = newVal.fileList;
  1264 |                     const index = files.findIndex(item => item.projectName == this.task.projectName);

error: Unexpected console statement (no-console) at src/components/project/taskDetail.vue:1262:21:
  1260 |                     //监听是否有上传文件行为
  1261 |                     console.log(newVal);
> 1262 |                     console.log(newVal.fileList);
       |                     ^
  1263 |                     const files = newVal.fileList;
  1264 |                     const index = files.findIndex(item => item.projectName == this.task.projectName);
  1265 |                     if (index !== -1) {

error: Unexpected console statement (no-console) at src/components/project/taskDetail.vue:1284:17:
  1282 |             };
  1283 |             document.onkeydown = (event) => {
> 1284 |                 console.log(event);
       |                 ^
  1285 |                 var e = event || window.event || arguments.callee.caller.arguments[0];
  1286 |                 if (13 == e.keyCode && e.ctrlKey) {
  1287 |                     //处理的部分

error: 'res' is defined but never used (no-unused-vars) at src/components/project/taskDetail.vue:1506:45:
  1504 |                     cancelText: `再想想`,
  1505 |                     onOk() {
> 1506 |                         del(app.code).then((res) => {
       |                                             ^
  1507 |                             ``
  1508 |                             app.detailClose();
  1509 |                         });

7 errors found.

Module Warning (from ./node_modules/eslint-loader/index.js):
error: 'to' is defined but never used (no-unused-vars) at src/components/project/versionDetail.vue:595:20:
  593 |         },
  594 |         watch: {
> 595 |             $route(to, from) {
      |                    ^
  596 |                 // if (from.name == 'taskdetail') {
  597 |                 //     this.init();
  598 |                 // }

error: 'from' is defined but never used (no-unused-vars) at src/components/project/versionDetail.vue:595:24:
  593 |         },
  594 |         watch: {
> 595 |             $route(to, from) {
      |                        ^
  596 |                 // if (from.name == 'taskdetail') {
  597 |                 //     this.init();
  598 |                 // }

error: 'res' is defined but never used (no-unused-vars) at src/components/project/versionDetail.vue:752:45:
  750 |                     cancelText: `再想想`,
  751 |                     onOk() {
> 752 |                         del(app.code).then((res) => {
      |                                             ^
  753 |                             ``
  754 |                             app.detailClose();
  755 |                         });

error: 'res' is defined but never used (no-unused-vars) at src/components/project/versionDetail.vue:785:88:
  783 | 
  784 |                 } else {
> 785 |                     changeStatus({versionCode: this.version.code, status: e.key}).then(res => {
      |                                                                                        ^
  786 |                         this.getVersion();
  787 |                     });
  788 |                 }

error: 'res' is defined but never used (no-unused-vars) at src/components/project/versionDetail.vue:801:37:
  799 |                                 status: this.publishVersion.status,
  800 |                                 publishTime: obj.publishTime,
> 801 |                             }).then(res => {
      |                                     ^
  802 |                                 app.publishVersion.modalStatus = false;
  803 |                                 app.getVersion();
  804 |                             });

5 errors found.

Module Warning (from ./node_modules/eslint-loader/index.js):
error: 'to' is defined but never used (no-unused-vars) at src/views/home/index.vue:234:31:
  232 |         },
  233 |         watch:{
> 234 |             $route: function (to, from) {
      |                               ^
  235 |                 this.init();
  236 |             },
  237 |             socketAction(val) {

error: 'from' is defined but never used (no-unused-vars) at src/views/home/index.vue:234:35:
  232 |         },
  233 |         watch:{
> 234 |             $route: function (to, from) {
      |                                   ^
  235 |                 this.init();
  236 |             },
  237 |             socketAction(val) {

error: Unexpected console statement (no-console) at src/views/home/index.vue:238:17:
  236 |             },
  237 |             socketAction(val) {
> 238 |                 console.log(val);
      |                 ^
  239 |                 if (val.action === 'organization:task') {
  240 |                     this.init(false, false);
  241 |                 }

3 errors found.

Module Warning (from ./node_modules/eslint-loader/index.js):
error: 'tokenList' is defined but never used (no-unused-vars) at src/store/mutations.js:2:24:
  1 | export default {
> 2 |     SET_LOGGED(state, {tokenList, userInfo}) {
    |                        ^
  3 |         state.logged = true;
  4 |         state.userInfo = userInfo;
  5 |     },

1 error found.

Module Warning (from ./node_modules/eslint-loader/index.js):
error: 'val' is defined but never used (no-unused-vars) at src/components/project/recycleBin.vue:92:20:
  90 |                 this.init();
  91 |             },
> 92 |             tabKey(val) {
     |                    ^
  93 |                 this.init();
  94 |             }
  95 | 

1 error found.

Module Warning (from ./node_modules/eslint-loader/index.js):
error: 'values' is defined but never used (no-unused-vars) at src/views/account/setting/security.vue:348:27:
  346 |                 let app = this;
  347 |                 this.form.validateFields(
> 348 |                     (err, values) => {
      |                           ^
  349 |                         if (!err) {
  350 |                             let obj = app.form.getFieldsValue();
  351 |                             if (obj.password.length < 6 || obj.newPassword.length < 6 || obj.confirmPassword.length < 6) {

error: 'values' is defined but never used (no-unused-vars) at src/views/account/setting/security.vue:379:27:
  377 |                 let app = this;
  378 |                 this.mobileForm.validateFields(
> 379 |                     (err, values) => {
      |                           ^
  380 |                         if (!err) {
`
大佬有空帮忙看看嘛

**Comment by a54552239** [comment]
这些是语法警告，可以先忽略
