### ISSUE TITLE
企业微信中浏览页面问题

### ISSUE THREAD

**Issue by zhf883680** [a54552239/pearProject#55]
企业微信中浏览 输入框消失
![image](https://user-images.githubusercontent.com/23031238/119760854-5e0ea500-bedd-11eb-80c5-026a018de47d.png)
![image](https://user-images.githubusercontent.com/23031238/119760862-623ac280-bedd-11eb-956e-f53aaf9fa62b.png)

**Comment by a54552239** [comment]
估计是浏览器内核不兼容
