### ISSUE TITLE
无法构建

### ISSUE THREAD

**Issue by desire599** [a54552239/pearProject#59]
当使用`npm run serve`或`build`报一系列的找不到vue
如下:
` warning  in ./node_modules/ant-design-vue/es/vc-trigger/Popup/PopupInner.js  "export 'withModifiers' was not found in 'vue'`
![image](https://user-images.githubusercontent.com/56039867/164763770-e76484e9-02c6-40bc-bfb8-57481fc4ce04.png)
 尝试修改模块的中的版本 一个一个排除仍未解决

**Comment by 839536** [comment]
Thank you. Your email is received and will be handled  as soon as possible.

**Comment by mirZY** [comment]
Has this problem been solved？

**Comment by a54552239** [comment]
# #60
