### ISSUE TITLE
演示地址一片空白

### ISSUE THREAD

**Issue by ckinmind** [a54552239/pearProject#8]

**Comment by a54552239** [comment]
是基于什么浏览器访问的？

**Comment by ckinmind** [comment]
@a54552239 chrome浏览器 版本75，基本上是最新的，页面访问`https://beta.vilson.xyz/#/home`页面内容一闪而逝

**Comment by a54552239** [comment]
清除一下浏览器缓存后再试试

**Comment by ckinmind** [comment]
![image](https://user-images.githubusercontent.com/8199343/61194383-a65eb880-a6f3-11e9-9532-e3a14cf83138.png)

 清除缓存后，有这个错误，而且只有清除缓存后第一次访问才有这个错误@a54552239

**Comment by a54552239** [comment]
这里是用于钉钉环境下自动登录的，暂时可以不用理会

**Comment by ckinmind** [comment]
@a54552239 沟通起来是真的有点累，我只是想体验下项目的演示环境，访问进去啥也看不到，我当然可以不理会错误，但是关键是页面一片空白无法访问，所以沟通了半天，我既感觉不到我提的这个issue对你有什么帮助，更加感觉不到你想要去解决这个问题

**Comment by a54552239** [comment]
感谢你的反馈，我这边看下如何复现你遇到的情况

**Comment by hVenus** [comment]
同样的错误。能不能先把钉钉这东西关掉。

**Comment by a54552239** [comment]
感谢反馈，已做兼容处理。[https://github.com/a54552239/pearProject/commit/e0faf123ad8e273ad6ff29229364f16f6b68b1c1](url)

**Comment by ckinmind** [comment]
项目的演示地址访问仍然是一片空白，摊手.....

**Comment by karong398** [comment]
你好，麻烦将我从收件人列表移除，谢谢


李培
13422353612



在2019年08月7日 14:35，CK<notifications@github.com> 写道：

项目的演示地址访问仍然是一片空白，摊手.....
